name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3

    - name: make
      run: make 

    - uses: actions/download-artifact@main
      with:
        path: build
